### ISSUE TITLE
Unable to open file for editing

### ISSUE THREAD

**Issue by BNNorman** [joewez/AmpyFileManager#4]
I thought this would make life a little less painful but the one major use case is broken.
When I double-click or highlight a file and click open the editor window remains blank.

I can create and save a new file - the new file saves in the PC session folder as well, So I tried putting files I wanted to edit in the session folder but that didn't work.

I am using Windows 10 64bit.

My current project involves three files so I don't want to create-new-paste-save each time.

Is there something I could do to get this functionality to work? I am using the precompiled EXE not building from source.
Thanks

**Comment by joewez** [comment]
One possibility is the version of AMPY you are running.  They have made alot of changes recently that may affect certain functions of the application.  First confirm the version you are running by entering the command at a command prompt...

     `ampy --version`

 I run version 1.05 and it seems to work fine.  If you want to try another version of ampy...

    `pip uninstall adafruit-ampy`
    `pip install adafruit-ampy==1.0.5`

Hope this resolves your issue.  If not I will make sure the EXE is the correct one.

**Comment by BNNorman** [comment]
It was version 1.0.7 - installed 1.0.5 and it worked ok. Thank you for your quick response.

I wonder what they broke?

**Comment by joewez** [comment]
It will actually be improved as it goes on.
Since Adafruit abandoned the project a couple of months ago, someone else has picked up the development.  They are changing some of the way some of the commands work so it affects this application.
I will monitor the changes and when it reaches some stability I will update AmpyFileManager to work with it.

BTW: Thanks for you feedback!

**Comment by joewez** [comment]
I have updated the app to work with the latest version of AMPY.
